### PR TITLE
Add support for `cause()` when error is Box<Error>

### PR DESCRIPTION
**Pull request by Byron**
Sometimes one wants to support any kind of error, and without
support for generics, using a `Box` is the only way.

Previously `cause(err)` would not work as one cannot automatically
convert `Box<Error>` into `Option<&Error>`. However, the `Borrow`
trait will make it work for boxes as well as for simple references.

Please note that the current implementation does not (yet) support
partial equality.

Thanks to [Francis Gagné](http://stackoverflow.com/questions/38842875/how-to-use-quick-error-with-boxed-error-types/38885994#38885994) for helping me figuring it out.

### CODE REVIEW

**Comment by colin-kiegel** [comment]
Looks good to me.

@tailhook just out of curiosity, why did you disable travis for pull requests?

**Comment by Byron** [comment]
@tailhook @colin-kiegel Is there anything you need to get this merged ? Thank you.

**Comment by colin-kiegel** [comment]
@Byron After second thought maybe one detail could be changed. `Box<T>` and `T` both implement `Borrow<T>` and `AsRef<T>`. And the corresponding methods have [identical signatures and implementation](https://doc.rust-lang.org/src/alloc/up/src/liballoc/boxed.rs.html#623) in this case, i.e. they are completely exchangeable. However they express slightly different intentions. IMO `AsRef` expresses the intention in this case better than `Borrow`. I suggest to switch to `AsRef`.

You can find the explanation of the different intentions in [the book](https://doc.rust-lang.org/book/borrow-and-asref.html#which-should-i-use).

Note: I am only another contributor (like you), without write permissions to this repository. So I can participate in the discussion, but only @tailhook can merge if he approves. ;-)

**Comment by Byron** [comment]
@colin-kiegel I agree, `as_ref()` seems more suited in this case. However, when testing it, it didn't appear to be working, even though I didn't delve into the details as to why that is.
Maybe you have an idea how to get this to work:
<details>

``` diff
diff --git a/src/lib.rs b/src/lib.rs
index 2331655..832c495 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -629,7 +629,7 @@ macro_rules! quick_error {
         [$( $var:ident ),*]
         { cause($expr:expr) $( $tail:tt )*}
     ) => {
-        Some($expr.borrow())
+        Some($expr.as_ref())
     };
     (FIND_CAUSE_IMPL $item:ident: $imode:tt
         [$( $var:ident ),*]
```

<details>

```
   Compiling quick-error v1.1.0 (file:///Users/byron/dev/rs/quick-error)
error: no method named `as_ref` found for type `&std::num::ParseFloatError` in the current scope
   --> src/lib.rs:632:20
    |
632 |         Some($expr.as_ref())
    |                    ^^^^^^
src/lib.rs:638:9: 640:27 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:638:9: 640:27 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:560:29: 562:48 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:309:9: 311:17 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:324:9: 327:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:324:9: 327:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:266:9: 268:36 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:939:5: 967:6 note: in this expansion of quick_error! (defined in src/lib.rs)
    |
    = note: the method `as_ref` exists but the following trait bounds were not satisfied: `std::num::ParseFloatError : std::convert::AsRef<_>`

error: no method named `as_ref` found for type `&std::str::Utf8Error` in the current scope
   --> src/lib.rs:632:20
    |
632 |         Some($expr.as_ref())
    |                    ^^^^^^
src/lib.rs:560:29: 562:48 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:309:9: 311:17 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:324:9: 327:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:369:9: 373:11 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:324:9: 327:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:266:9: 268:36 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:939:5: 967:6 note: in this expansion of quick_error! (defined in src/lib.rs)
    |
    = note: the method `as_ref` exists but the following trait bounds were not satisfied: `std::str::Utf8Error : std::convert::AsRef<_>`

error: no method named `as_ref` found for type `&std::str::Utf8Error` in the current scope
   --> src/lib.rs:632:20
    |
632 |         Some($expr.as_ref())
    |                    ^^^^^^
src/lib.rs:560:29: 562:48 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:309:9: 311:17 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:396:9: 399:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:410:9: 414:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:383:9: 386:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:337:9: 341:34 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:266:9: 268:36 note: in this expansion of quick_error! (defined in src/lib.rs)
src/lib.rs:1035:5: 1051:6 note: in this expansion of quick_error! (defined in src/lib.rs)
    |
    = note: the method `as_ref` exists but the following trait bounds were not satisfied: `std::str::Utf8Error : std::convert::AsRef<_>`

error: aborting due to 3 previous errors

error: Could not compile `quick-error`.

To learn more, run the command again with --verbose.
```

**Comment by colin-kiegel** [comment]
@Byron My mistake - `AsRef` is _not_ implemented for `T` or `&T`, that's why it doesn't work - contrary to my previous claim. I guess the best choice would be `std::ops::Deref::deref()` then:
https://play.rust-lang.org/?gist=6d3eefc7a509513537d0dc4fdac0e570&version=stable&backtrace=0

Note that you can write `&**y` instead of `y.deref()`.

**Comment by tailhook** [comment]
Sorry for late reply.

@colin-kiegel at a glance it looks like that difference is that `deref` is always dereferenced to a specific associated type, while `borrow` is a generic that can probably defererence to different things depending on type inference. It looks like `deref` is not implemented for `T` too. So `borrow` is right choice here.

Still, I'm not convinced it's necessary. It's easy to write `.borrow()` or `.deref()` yourself. And I'm not sure if this change doesn't break any existing usage (because of some type inference rules)

At the end of the day, I'm not sure either way since `quick-error` crate is here exactly to shorten the boilerplate.

**Comment by colin-kiegel** [comment]
@tailhook First things first - the most important question probably is: Would you agree, that @Byron has a valid use-case, when doing something like this?

``` rust
pub enum MyError {
    // ... some fields elided
    Any(Box<::std::error::Error>),
}
```

quick-error currently fails to implement the `cause()` method for a definition like this. Here is a simplified example of the generated code of quick-error ([playground example](https://play.rust-lang.org/?gist=e268020f9a5ffedf3d2fbd4efee39a3c&version=stable&backtrace=0)):

```
error: the trait bound `std::error::Error + 'static: std::marker::Sized` is not satisfied [--explain E0277]
  --> <anon>:15:43
   |>
15 |>             MyError::Any(ref err) => Some(err),
   |>                                           ^^^
note: `std::error::Error + 'static` does not have a constant size known at compile-time
note: required because of the requirements on the impl of `std::error::Error` for `Box<std::error::Error + 'static>`
note: required for the cast to the object type `std::error::Error`
```

Translated to plain english, this means: There _is_ a generic implementation of `Error` for `Box<T: Error>`, where `T: Error`. But `T` may _not_ be a trait object (=unsized). So this would only work, if @Byron switches to a generic error definition like this one ([playground example](https://play.rust-lang.org/?gist=b2a5ec50b1f4f454889004fe8b2fa451&version=stable&backtrace=0)):

``` rust
pub enum MyError<T: ::std::error::Error + Sized> {
    Any(Box<T>),
}
```

If @Byron wants to solve this via using `.borrow()` or `.deref()` explicitly, this would require him to _not_ use quick-error.

I see these options:
1. User solves this
   1. don't use quick-error
   2. use generic enums
2. quick-error solves this
   1. with borrow
   2. with deref

I would still vote for deref. Deref is actually a pointer abstraction, it means anything that implements `Deref<Target=T>` is conceptually a pointer to `T`. It unifies builtin pointers like `&T` and `&mut T` and `Rc<T>`, `Box<T>`. What deref does, is stripping all these smart-pointers away in a consistent way to get to `&T`.

Borrow is something different - _by it's definition_ Borrow should only be implemented, if `Hash`, `Eq` and/or `Ord` are implemented consistently for `X` and `&T`, where `X: Borrow<T>`. It's kind of a marker-trait for that. We don't need any of these constraints.

Let's get back to the example

```
pub enum MyError {
    Any(Foo),
}
```

I see it like this - to implement the `cause()` branch for the `Any(Foo)` variant, we require:
- `&Foo` must be any kind of generalized pointer `&Error`, `&&Error`, `&Rc<Error>`, etc. - we then can use deref to cast it to `&Error`.

PS: Sorry for the long post. :-)

**Comment by colin-kiegel** [comment]
PS: You are right, that `Deref` is not implemented for `T`, but this is sufficient:
- `impl<'a, T> Deref for &'a T where T: ?Sized`

It basically says: `&T` is a pointer to `T`. And this is all we need ([playground example](https://play.rust-lang.org/?gist=6d3eefc7a509513537d0dc4fdac0e570&version=stable&backtrace=0)]

**Comment by colin-kiegel** [comment]
Ok, I have changed my mind. :-)

For these reasons:
- What if people want to use variants like `Any(Box<Rc<Error>>)` - neither `deref` nor `borrow` seem to work here
- I somehow forgot that it is indeed possible to do it with quick-error, because we match on expressions and not idents: `cause(&**err)` in case of `Box<Err>`.
- There seems to be something wrong with deref and lifetimes in match statements (I currently suspect a rustc bug, but maybe I'm wrong)

https://play.rust-lang.org/?gist=b4707c4f49ce336c0db2dd90a0e73bb6&version=nightly&backtrace=0

This is working:

``` rust
#[macro_use] extern crate quick_error;

#[allow(dead_code)]
quick_error!{
    #[derive(Debug)]
    pub enum MyError {
        Any(err: Box<::std::error::Error>) {
            cause(&**err)
        }
    }
}

fn main() {}
```

@Byron Is it ok for you to do the deref/borrow (whatever you like) in the definition of the error? If this is good enough for you, you could still contribute by extending the examples and documentation for this case (@tailhook if that is ok for you ^^).

**Comment by colin-kiegel** [comment]
PS: The solution for something weird like `Box<Rc<Error>>` would be two `deref`s or `&**`s. Two `borrow`s will not work here, because this could be ambiguous.

**Comment by Byron** [comment]
@colin-kiegel Terrific work ! Thanks for figuring all this out ! I just pushed the fix for my codebase, and actually believe making this case more obvious or part of the main tutorial would help others, and make `quick-error` even more useful.
Before adjusting anything, I'd wait for @tailhook 's feedback though.

**Comment by tailhook** [comment]
Yes. This is actually a reason why there are expressions. I didn't realize that it isn't obvious.

In the cases above both deref and borrow works, but the downside is that you need to import those traits yourself. So `&**err` is a way to go.

I've added an example in 5d60010, if you think it's not enough, additions to the docs are always appreciated.

**Comment by Byron** [comment]
That totally works for me ! Thank you!
This PR is a great example on how to collaborate - it's a bit sad I have to close it now ;).

**Pull request closed without merging**
