### PR TITLE
Add compatibility with 'deny(rust_2018_idioms)'

### PR DESCRIPTION
**Pull request by Byron**
In crates with `#![forbid|deny(rust_2018_idioms)]` the code generated by the quick_error macro will now cause linter errors.

This commit turns these on in the crate itself and fixes them in two ways:

* blanket `#[allow(unused)]` was replaced with a more specific version
* the lifetime in std::fmt::Formatter types is declared

I hope a new patch release could be made if merging this PR is possible :).

### CODE REVIEW

**Comment by tailhook** [comment]
Looks good. But please submit PR without whitespace changes.

**Comment by Byron** [comment]
Sorry for that, 'format on save' is your friend until it isn't 🤦‍♂️.

I also tried, without success, to prevent rustfmt from touching the entire file _and failed_. That was a surprisingly unpolished experience or I shouldn't try such preposterous things early in the morning 😅.

**Comment by tailhook** [comment]
Merged. Thanks!

**Comment by tailhook** [comment]
Released as v2.0.1

**Pull request merged**
