### PR TITLE
Propagate variants attributes to method definitions.

### PR DESCRIPTION
**Pull request by Yamakaky**

### CODE REVIEW

**Comment by tailhook** [comment]
Can you add a test for this feature? I'm not sure what are these imeta parameters at all and how we can apply meta parameters to "methods" which aren't actually the methods.

**Comment by Yamakaky** [comment]
In fact, the attributes specified to the variants of the error were propagated to the enum definition but not to the various matches in the methods definitions.

**Comment by ticki** [comment]
Can this be merged yet, @tailhook?

**Comment by tailhook** [comment]
Well, sorry for being silent for so much time here.

The problem that might be with this PR, is that `cfg(xx)` meta attributes might work. But we need to figure out how all other things work, like `doc(..)` and what else can be on variants?

While it makes sense propagate conditional compilation attributes (i.e. `cfg(xx)`) to match statement, others should not be propagated there, right? Does rust somehow splits them as `meta` an `imeta` or does rust allows to put `doc(..)` comments on match statements? (sorry, hadn't had much time to test it yet)

**Comment by ticki** [comment]
`imeta` isn't a segment type, but a macro variable name. `rustc` expands document comments as `#[doc = "..."]`, which works on `item` segments (e.g. `impl`, `struct`, `enum`, etc. etc.). I'm not sure why you want it to work on `match` statements? It doesn't seem necessary to me? I might be missing something.

**Comment by tailhook** [comment]
> imeta isn't a segment type, but a macro variable name. rustc expands document comments as #[doc = "..."], which works on item segments (e.g. impl, struct, enum, etc. etc.).

Ah, right. I've misread it at a glance.

> I'm not sure why you want it to work on match statements? It doesn't seem necessary to me? I might be missing something.

It's there in this pull request:

https://github.com/tailhook/quick-error/pull/30/files#diff-b4aea3e418ccdb71239b96952d9cddb6R529

Because conditional compilation requires it:

https://github.com/tailhook/quick-error/pull/30/files#diff-b4aea3e418ccdb71239b96952d9cddb6R1144

So I guess this will break docstrings on variants (yet to check)

**Comment by tailhook** [comment]
From what I observe it works fine. Thanks, for contributing! Sorry for sooooo long delay.

**Comment by Yamakaky** [comment]
^^

**Pull request merged**
